#config_version=4
mode:
  start_events: game_started
  stop_events: game_ending
  stop_on_ball_end: False
  code: poker.poker
  priority: 200

extra_balls:
  poker_extra_ball:
    award_events: award_poker_eb

  special_award:
    award_events: special_award_eb

queue_event_player:
  extra_ball_awarded:
    queue_event: play_eb_slide
    events_when_finished:  eb_award_done

slide_player:
  eject_remain_slide:
    eject_saucer_slide:
      expire: 2s

#this is a queue'd event
  play_eb_slide:
    poker_eb_slide:
      expire: 2s

  extra_ball_lit_slide:
      poker_eb_warning_slide:
        expire: 2s

  special_lit_slide:
    special_is_lit_slide:
      expire: 2s

light_player:
  shoot_again_lit:
    l_shoot_again: ff

  shoot_again_off:
    l_shoot_again: 0

  hearts_eject_solid:
    l_ace_hearts: ff

  club_eject_solid:
    l_ace_clubs: ff

  spade_eject_solid:
    l_ace_spades: ff

  extra_ball_solid:
    l_extra_ball: ff

  extra_ball_off:
    l_extra_ball: 0

  special_lit:
    l_left_special: ff
    l_right_special: ff

  special_off:
    l_right_special: 0
    l_left_special: 0

  poker_light_clear:
    l_p_light: 0
    l_o_light: 0
    l_k_light: 0
    l_e_light: 0
    l_r_light: 0

  poker_light_1:
    l_p_light: ff
    l_o_light: 0
    l_k_light: 0
    l_e_light: 0
    l_r_light: 0

  poker_light_2:
    l_p_light: ff
    l_o_light: ff
    l_k_light: 0
    l_e_light: 0
    l_r_light: 0

  poker_light_3:
    l_p_light: ff
    l_o_light: ff
    l_k_light: ff
    l_e_light: 0
    l_r_light: 0

  poker_light_4:
    l_p_light: ff
    l_o_light: ff
    l_k_light: ff
    l_e_light: ff
    l_r_light: 0

  poker_light_5:
    l_p_light: ff
    l_o_light: ff
    l_k_light: ff
    l_e_light: ff
    l_r_light: ff

show_player:
  hearts_eject_flash:
    heart_eject_flash_show:
      speed: 2
      loops: -1

  hearts_eject_solid:
    heart_eject_flash_show:
      action: stop

  club_eject_flash:
    club_eject_flash_show:
      speed: 2
      loops: -1

  club_eject_solid:
    club_eject_flash_show:
      action: stop

  spade_eject_flash:
    spade_eject_flash_show:
      speed: 2
      loops: -1

  spade_eject_solid:
    spade_eject_flash_show:
      action: stop

  extra_ball_flash:
    extra_ball_flash_show:
      speed: 2
      loops: -1

  extra_ball_off:
    extra_ball_flash_show:
      action: stop

  extra_ball_solid:
    extra_ball_flash_show:
      action: stop

slides:
  poker_eb_slide:
    widgets:
      - type: text
        text: EXTRA BALL!!
        font_name: DS-DIGI
        font_size: 50
        y: 100
        anchor_y: bottom
  poker_eb_warning_slide:
    widgets:
      - type: text
        text: EXTRA BALL IS LIT!!
        font_name: DS-DIGI
        font_size: 50
        y: 100
        anchor_y: bottom
  eject_saucer_slide:
    widgets:
      - type: text
        text: (ejects_remaining) saucer ejects remaining
        font_name: DS-DIGI
        font_size: 50
        y: 100
        anchor_y: bottom
      - type: text
        text: to advance POKER lights
        font_name: DS-DIGI
        font_size: 50
        y: 20
        anchor_y: bottom
  special_is_lit_slide:
    widgets:
      - type: text
        text: SPECIAL IS LIT!
        font_name: DS-DIGI
        font_size: 50
        y: 100
        anchor_y: bottom
