#config_version=4
mode:
  start_events: ball_starting
  priority: 100

event_player:
  mode_base_started: flipper_on
  ball_ending: flipper_off
  tilt: flipper_off
  slam_tilt: filppers_off

sound_player:
#  mode_base_started:
#    jedirock1:
#      action: play
#      loops: -1

#  player_turn_stop:
#    jedirock1:
#      action: stop
#  ball_will_end:
#    jedirock1:
#      action: stop

#  mode_end_action:
#    jedirock1:
#      action: stop

#  mode_base_stopping:
#    jedirock1:
#      mode_end_action: stop

  s_left_kicker_active:
    standup_hit:
      action: play
      loops: 1
  s_top_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_top_right_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_lower_right_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_lower_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_left_center_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_right_center_standup_active:
    standup_hit:
      action: play
      loops: 1
  s_five_bank_standup_active:
    standup_hit:
      action: play
      loops: 1

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        font_name: DS-DIGI
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        font_name: DS-DIGI
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        font_name: DS-DIGI

scoring:
  s_left_kicker_active:
    score: 100
  s_top_standup_active:
    score: 10
  s_top_right_standup_active:
    score: 10
  s_lower_right_standup_active:
    score: 10
  s_lower_standup_active:
    score: 10
  s_left_center_standup_active:
    score: 10
  s_right_center_standup_active:
    score: 10
  s_five_bank_standup_active:
    score: 10

sound_pools:
   standup_hit:
     type: random
     simultaneous_limit: 3
     stealing_method: skip
     sounds:
        - blast1
        - blast2
        - blast3
        - blast4
