#config_version=4
mode:
  start_events: ball_starting
  stop_events: ball_ended
  code: jetbumpers.jetbumpers
  priority: 150

light_player:
  jets_lvl_2:
      l_left_jet_bumper: ff
      l_center_jet_bumper: ff
      l_right_jet_bumper: ff
      l_bottom_jet_bumper: ff

show_player:
  jets_lvl_3:
    jetbumper_flash_1:
      speed: 5
      loops: -1

  jets_at_max:
    jetbumper_flash_2:
      speed: 6
      loops: -1



slide_player:
      jetcountdown:  #event that triggers
        jetcounter_slide:  #slide event calls
          expire: 2s #show the slide for two seconds

      jet_level_increase:
        jet_level_increase_slide:
          expire: 2s

      jets_at_max:
        jets_maximum_slide:
          expire: 2s

slides:
  jetcounter_slide: #this slide is shown when the bumpers hit
      widgets:
      - type: text
      #the remaining variable gets passed from jetcounter
      #Us the event viewer in monitor to check for avaliable values
        text: (jetsremain) hits left to level up
        font_name: DS-DIGI
        font_size: 75
        y: 70
        anchor_y: bottom

  jet_level_increase_slide:
      widgets:
      - type: text
        text: Jets now Level (jetlevel)!
        font_size: 75
        font_name: DS-DIGI
        y: 70
        anchor_y: bottom

  jets_maximum_slide:
    widgets:
      - type: text
        text: JETBUMPERS AT MAXIMUM!
        font_size: 75
        font_name: DS-DIGI
        y: 70
        anchor_y: bottom
