#config_version=4
mode:
  start_events: mode_base_started
  #stop_events: ball_ended.1
  #stop_on_ball_end: False
  code: bonus.bonus
  priority: 200

#this is setup to work with the bonus award mode
#this pauses the event queue while the bonus award
#mode starts up, and awards the bonus
queue_relay_player:
  ball_ending:
    post: bonus_award_1
    wait_for:   slide_bonus_award_1_slide_removed

slide_player:
  bonus_x_increase:
    bonus_x_slide:
      expire: 2s

slides:
  bonus_x_slide:
    widgets:
      - type: text
        text: (bonus_x)X Bonus!
        font_name: DS-DIGI
        font_size: 50
        y: 100
        anchor_y: bottom
